version: '3'

services:
  app:
    build: .
    ports:
     - "5000:5000"
     - "3000:3000"
     - "3001:3001"
     - "3002:3002"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=root
      - DB_PASS=123123123
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
